language: python
python:
    - 2.7

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libev-dev
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install pyev; fi
    - pip install --use-mirrors -r test-requirements.pip
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform


services:
  - rabbitmq
script: 
  - nosetests -c nose.cfg --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_pika_69a1f46dcf_3
  - python -m properform Push 47.88.50.110:15554 asdf_pika_69a1f46dcf_3 ./profile_pika_69a1f46dcf_3

 #2017-08-13 13:04:53 modified at 0 #2017-08-13 13:04:57 modified at 1 #2017-08-13 13:05:01 modified at 2 #2017-08-13 13:05:05 modified at 3