language: python

os:
  - linux

python:
  - 2.7


matrix:
  include:
    - os: osx
      # Cursory validation on osx, but only with python 3 (to avoid builds taking too long)
      # Workaround for Tavis's current lack of official support for Python on OS X
      # Reference https://github.com/travis-ci/travis-ci/issues/2312
      language: generic
      before_install:
        - brew update
        - brew install libev
        - brew install python3
        - virtualenv env -p python3
        - source env/bin/activate
        - echo Installing RabbitMQ...
        - brew install rabbitmq
        - echo Starting RabbitMQ...
        - export PATH="${PATH}:/usr/local/sbin"
        - sudo rabbitmq-server -detached

before_install:
  - echo Installing libev on Linux...
  - sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ trusty main restricted universe multiverse"
  - sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ trusty-updates main restricted universe multiverse"
  - sudo apt-get update -qq
  - sudo apt-get install libev-dev/trusty
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - which -a python
  - python --version
  - which pip
  - pip --version
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2 ordereddict; fi
  - if [[ $TRAVIS_PYTHON_VERSION != '2.6' ]]; then pip install pyev; fi
  - pip install -r test-requirements.txt
  - pip freeze
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform

services:
  - rabbitmq

script:
  - sudo rabbitmqctl status
  - nosetests --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_pika_14a73f9228_2
  - python -m properform Push 47.88.50.110:15554 asdf_pika_14a73f9228_2 ./profile_pika_14a73f9228_2


after_success:
  - codecov

 #2017-08-13 12:09:42 modified at 0 #2017-08-13 12:09:47 modified at 1 #2017-08-13 12:09:51 modified at 2