language: python
python:
    - 2.7

before_install:
       # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors unittest2; fi
    - pip install --use-mirrors tornado twisted pyyaml 
    # add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform

script: 
  - nosetests --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_pika_5993a13a54_4
  - python -m properform Push 47.88.50.110:15554 asdf_pika_5993a13a54_4 ./profile_pika_5993a13a54_4

 #2017-08-13 13:14:53 modified at 0 #2017-08-13 13:14:58 modified at 1 #2017-08-13 13:15:02 modified at 2 #2017-08-13 13:15:07 modified at 3 #2017-08-13 13:15:11 modified at 4