language: python
python:
    - 2.7

before_install:
    - sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ trusty main restricted universe multiverse"
    - sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ trusty-updates main restricted universe multiverse"
    - sudo apt-get update -qq
    - sudo apt-get install libev-dev/trusty
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2 ordereddict; fi
    - if [[ $TRAVIS_PYTHON_VERSION != '2.6' ]]; then pip install pyev; fi
    - pip install -r test-requirements.txt
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform


services:
  - rabbitmq
script: 
  - nosetests -c nose.cfg --with-coverage --cover-package=pika --cover-branches --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_pika_0343c5cc7b_3
  - python -m properform Push 47.88.50.110:15554 asdf_pika_0343c5cc7b_3 ./profile_pika_0343c5cc7b_3


after_success:
  - codecov

 #2017-08-13 12:31:49 modified at 0 #2017-08-13 12:31:54 modified at 1 #2017-08-13 12:31:58 modified at 2 #2017-08-13 12:32:02 modified at 3