language: python
python:
    - 2.7


before_install:
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors unittest2; fi
    - apt-get -y install libev
    - pip install --use-mirrors -r test-requirements.pip
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform


services:
  - rabbitmq
script: 
  - nosetests -c nose.cfg --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_pika_a75f693c70_2
  - python -m properform Push 47.88.50.110:15554 asdf_pika_a75f693c70_2 ./profile_pika_a75f693c70_2
 #2017-08-13 13:06:43 modified at 0 #2017-08-13 13:06:48 modified at 1 #2017-08-13 13:06:52 modified at 2